language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t client/dockertest -f Dockerfile  .

script:
  - docker run -e CI=true client/dockertest npm run test

after_success:
  - docker build -t client/dockertest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push client/dockertest